package:
  format-version: "1.0.0"
  name: "wireless_zigbee"
  type: "package"
  status: "production"
  required: false
  version: "v5.1.1"

  dependencies:
    - name: "csp"
      type: "package"
      version: "v3.17.0"
    - name: "bsp"
      type: "package"
      version: "v3.16.0"
    - name: "core"
      type: "package"
      version: "v3.13.0"
    - name: "crypto"
      type: "package"
      version: "v3.8.0"
    - name: "CMSIS-FreeRTOS"
      type: "package"
      version: "v10.3.1"
    - name: "zlib"
      type: "package"
      version: "v1.2.13"
    - name: "wireless_pic32cxbz_wbz"
      type: "package"
      version: "v1.2.0"      
    - name: "wolfssl"
      type: "package"
      version: "v4.8.1"
