package:
  format-version: "1.0.0"
  name: "wireless_zigbee"
  type: "package"
  status: "production"
  required: true
  version: "5.1.0"

  dependencies:
    - name: "csp"
      type: "package"
      version: "3.17.0"
    - name: "dev_packs"
      type: "package"
      version: "3.17.0"
    - name: "bsp"
      type: "package"
      version: "3.16.0"
    - name: "core"
      type: "package"
      version: "3.13.0"
    - name: "crypto"
      type: "package"
      version: "3.8.0"
    - name: "CMSIS-FreeRTOS"
      type: "package"
      version: "10.3.1"
    - name: "zlib"
      type: "package"
      version: "1.2.13"
    - name: "mhc"
      type: "package"
      version: "3.8.3"
    - name: "wireless_pic32cxbz_wbz"
      type: "package"
      version: "1.2.0"      
    - name: "wolfssl"
      type: "package"
      version: "4.8.1"
