package:
  format-version: "1.0.0"
  name: "wireless_zigbee"
  type: "package"
  status: "production"
  required: false
  version: "6.0.0"

  dependencies:
    - name: "wireless_pic32cxbz_wbz"
      type: "package"
      version: "v1.3.0"    