/*******************************************************************************
  Extended Color Light Identify cluster Source File

  Company:
    Microchip Technology Inc.

  File Name:
   eclIdentifyCluster.c

  Summary:
    This file contains the Extended Color Light Identify cluster interface.

  Description:
    This file contains the Extended Color Light Identify cluster interface.
 *******************************************************************************/

// DOM-IGNORE-BEGIN
/*******************************************************************************
* Copyright (C) 2018 Microchip Technology Inc. and its subsidiaries.
*
* Subject to your compliance with these terms, you may use Microchip software
* and any derivatives exclusively with Microchip products. It is your
* responsibility to comply with third party license terms applicable to your
* use of third party software (including open source software) that may
* accompany Microchip software.
*
* THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES, WHETHER
* EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED
* WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A
* PARTICULAR PURPOSE.
*
* IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE,
* INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND
* WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS
* BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE. TO THE
* FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS IN
* ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF ANY,
* THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
*******************************************************************************/
// DOM-IGNORE-END

#ifdef APP_DEVICE_TYPE_EXTENDED_COLOR_LIGHT

/******************************************************************************
                    Includes section
******************************************************************************/
#include <eclIdentifyCluster.h>
#include <identifyCluster.h>

#include <eclLevelControlCluster.h>
#include <eclColorControlCluster.h>

#include <z3Device.h>
#include <haClusters.h>

#include <uartManager.h>
#include <commandManager.h>
#include <ezModeManager.h>

#include <pdsDataServer.h>

#include <leds.h>

#ifdef BOARD_MEGARF
  #include <buttonsExt.h>
#endif
#if defined(BOARD_MEGARF) || defined(BOARD_SAMR21)
  #include <ledsExt.h>
  #include <lcdExt.h>
#endif


/******************************************************************************
                    Definition(s) section
******************************************************************************/
#define DEFAULT_IDENTIFY_TIME        3U

#define BLINK_IDENTIFY_TIME          1U
#define BREATHE_IDENTIFY_TIME        15U
#define OKAY_IDENTIFY_TIME           1U
#define CHANNEL_CHANGE_IDENTIFY_TIME 8U

#define ENHANCED_HUE_GREEN           30000U
#define ENHANCED_HUE_ORANGE          5000U

/******************************************************************************
                    Prototypes section
******************************************************************************/

// Commands received by server
static ZCL_Status_t identifyInd(ZCL_Addressing_t *addressing, uint8_t payloadLength, ZCL_Identify_t *payload);
static ZCL_Status_t identifyQueryInd(ZCL_Addressing_t *addressing, uint8_t payloadLength, uint8_t *payload);
static ZCL_Status_t triggerEffectInd(ZCL_Addressing_t *addressing, uint8_t payloadLength, ZCL_TriggerEffect_t *payload);
static ZCL_Status_t identifyQueryResponseInd(ZCL_Addressing_t *addressing, uint8_t payloadLength, ZCL_IdentifyQueryResponse_t *payload);
// Commands generated by client
static ZCL_Status_t sendIdentifyQueryResponse(ZCL_Addressing_t *addressing);

// Support functions
static void eclFillIdentifyQueryResponsePayload(ZCL_IdentifyQueryResponse_t *payload, uint16_t time);
//static void fillIdentifyPayload(ZCL_Identify_t *payload, uint16_t time);
//static void (*identifycb)(void);

// Indication to notify change in Identify cluster attributes
static void ZCL_IdentifyAttributeEventInd(ZCL_Addressing_t *addressing, ZCL_AttributeId_t attributeId, ZCL_AttributeEvent_t event);

// Timer related function
static void effectTimerFired(void);
static void (*identifycb)(void);

/******************************************************************************
                    Global variables section
******************************************************************************/
ZCL_IdentifyClusterServerAttributes_t eclIdentifyClusterServerAttributes =
{
  ZCL_DEFINE_IDENTIFY_CLUSTER_SERVER_ATTRIBUTES()
};

ZCL_IdentifyClusterClientAttributes_t eclIdentifyClusterClientAttributes =
{
  ZCL_DEFINE_IDENTIFY_CLUSTER_CLIENT_ATTRIBUTES()
};

ZCL_IdentifyClusterCommands_t   eclIdentifyCommands =
{
  ZCL_IDENTIFY_CLUSTER_COMMANDS(identifyInd, identifyQueryInd, triggerEffectInd, identifyQueryResponseInd)
};

/******************************************************************************
                    Static variables section
******************************************************************************/
static HAL_AppTimer_t effectTimer;

static struct
{
  bool period      : 1;
  bool finish      : 1;
  bool colorEffect : 1;
} identificationStatus;

static DECLARE_QUEUE(subscribers);

/******************************************************************************
                    Implementation section
******************************************************************************/
/**************************************************************************//**
\brief Initializes Identify cluster
******************************************************************************/
void identifyClusterInit(void)
{
  ZCL_Cluster_t *cluster = ZCL_GetCluster(APP_ENDPOINT_EXTENDED_COLOR_LIGHT, IDENTIFY_CLUSTER_ID, ZCL_CLUSTER_SIDE_SERVER);

  if (cluster)
  {
    cluster->ZCL_AttributeEventInd = ZCL_IdentifyAttributeEventInd;
  }

  identifyStop();

  // Reset attributes
  eclIdentifyClusterServerAttributes.identifyTime.value = 0;
  eclIdentifyClusterServerAttributes.clusterVersion.value = 1u;
  eclIdentifyClusterClientAttributes.clusterVersion.value = 1u;
}

/**************************************************************************//**
\brief Checks if identification process is in progress

\returns true if it is, false otherwise
******************************************************************************/
bool identifyIsIdentifying(void)
{
  return eclIdentifyClusterServerAttributes.identifyTime.value > 0;
}

/**************************************************************************//**
\brief Shows identification effect in way specified.

\param[in] identifyTime - identifying period in seconds.
\param[in] colorEffect - flag to set for color effects.
\param[in] enhancedHue - enhanced hue to move for color effects.
******************************************************************************/
void identifyStart(uint16_t identifyTime, bool colorEffect, uint16_t enhancedHue)
{
  HAL_StopAppTimer(&effectTimer);
  identificationStatus.finish = false;
  identificationStatus.colorEffect = colorEffect;

  if (colorEffect)
  {
    eclIdentifyClusterServerAttributes.identifyTime.value = identifyTime * 2;
    colorControlShowIdentifyEffect(enhancedHue);
  }
  else
  {
    eclIdentifyClusterServerAttributes.identifyTime.value = identifyTime;
  }

  LCD_FILL(true);
  LEDS_SET_BRIGHTNESS(MAX_LIGHT_LEVEL);

  effectTimer.mode = TIMER_REPEAT_MODE;
  effectTimer.interval = 500;
  effectTimer.callback = effectTimerFired;

  HAL_StartAppTimer(&effectTimer);
}


/**************************************************************************//**
\brief Callback on receiving Identify Query Response command

\param[in] addressing - pointer to addressing information;
\param[in] payloadLength - data payload length;
\param[in] payload - data pointer

\return status of indication routine
******************************************************************************/
static ZCL_Status_t identifyQueryResponseInd(ZCL_Addressing_t *addressing, uint8_t payloadLength, ZCL_IdentifyQueryResponse_t *payload)
{
  appSnprintf("->Identify Query Response, addr = %d, timeout = 0x%04x\r\n", addressing->addr.shortAddress, payload->timeout);

  RAISE_CALLBACKS_TO_IDENTIFY_SUBSCIBERS(subscribers, identifyQueryResponse);

  (void)addressing, (void)payloadLength, (void)payload;
  return ZCL_SUCCESS_STATUS;
}

/**************************************************************************//**
\brief Finish identification routine.
******************************************************************************/
void identifyFinish(void)
{
  identificationStatus.finish = true;
}

/**************************************************************************//**
\brief Stop identification routine.
******************************************************************************/
void identifyStop(void)
{
  if (identificationStatus.colorEffect)
    colorControlStopIdentifyEffect();

  identificationStatus.period = 0;

  HAL_StopAppTimer(&effectTimer);
  eclIdentifyClusterServerAttributes.identifyTime.value = 0;

  LCD_FILL(false);
  levelControlDisplayLevel();
}

/**************************************************************************//**
\brief Effect timer callback
******************************************************************************/
static void effectTimerFired(void)
{
  if (identificationStatus.colorEffect)
  {
    eclIdentifyClusterServerAttributes.identifyTime.value--;
  }
  else
  {
    uint8_t level = 0;
    identificationStatus.period = !identificationStatus.period;

    LCD_FILL(identificationStatus.period);

    if (identificationStatus.period)
    {
      level = MAX_LIGHT_LEVEL;
      eclIdentifyClusterServerAttributes.identifyTime.value--;
    }

    LEDS_SET_BRIGHTNESS(level);

    (void)level;
  }

  if ((0 == eclIdentifyClusterServerAttributes.identifyTime.value) || (identificationStatus.finish))
  {
    identifyStop();
    if (identifycb)
    {
      identifycb();
    }
  }
}

/**************************************************************************//**
\brief Attribute event (writing/reading) callback.

\param[in] addressing - incoming request addressing information.
\param[in] attributeId - attribute identifier.
\param[in] event - attribute event (read/write).
******************************************************************************/
static void ZCL_IdentifyAttributeEventInd(ZCL_Addressing_t *addressing, ZCL_AttributeId_t attributeId, ZCL_AttributeEvent_t event)
{
  if ((ZCL_WRITE_ATTRIBUTE_EVENT == event) && (ZCL_IDENTIFY_CLUSTER_IDENTIFY_TIME_ATTRIBUTE_ID == attributeId))
  {
    if (eclIdentifyClusterServerAttributes.identifyTime.value)
    {
      identifyStart(eclIdentifyClusterServerAttributes.identifyTime.value, IDENTIFY_NON_COLOR_EFFECT, 0);
    }
    else
    {
      identifyStop();
    }

    (void)addressing;
  }
}

/**************************************************************************//**
\brief Callback on receiving Identify command

\param[in] addressing - pointer to addressing information;
\param[in] payloadLength - data payload length;
\param[in] payload - data pointer

\return status of indication routine
******************************************************************************/
static ZCL_Status_t identifyInd(ZCL_Addressing_t *addressing, uint8_t payloadLength, ZCL_Identify_t *payload)
{
  appSnprintf("Identify\r\n");

  eclIdentifyClusterServerAttributes.identifyTime.value = payload->identifyTime;

  if (payload->identifyTime)
    identifyStart(payload->identifyTime, IDENTIFY_NON_COLOR_EFFECT, 0);
  else
    identifyStop();

//  RAISE_CALLBACKS_TO_IDENTIFY_SUBSCIBERS(subscribers, identify);

  (void)addressing, (void)payloadLength;
  return ZCL_SUCCESS_STATUS;
}

/**************************************************************************//**
\brief Callback on receiving Identify Query command

\param[in] addressing - pointer to addressing information;
\param[in] payloadLength - data payload length;
\param[in] payload - data pointer

\return status of indication routine
******************************************************************************/
static ZCL_Status_t identifyQueryInd(ZCL_Addressing_t *addressing, uint8_t payloadLength, uint8_t *payload)
{
  if (eclIdentifyClusterServerAttributes.identifyTime.value)
    return sendIdentifyQueryResponse(addressing);

  RAISE_CALLBACKS_TO_IDENTIFY_SUBSCIBERS(subscribers, identifyQuery);

  (void)payload, (void)payloadLength;
  return ZCL_SUCCESS_STATUS;
}


/**************************************************************************//**
\brief Callback on receive of Trigger Effect command
******************************************************************************/
static ZCL_Status_t triggerEffectInd(ZCL_Addressing_t *addressing, uint8_t payloadLength, ZCL_TriggerEffect_t *payload)
{
  appSnprintf("TriggerEffect %d\r\n",  payload->effectIdentifier);

  (void)addressing;
  (void)payload;
  return ZCL_SUCCESS_STATUS;
}

/**************************************************************************//**
\brief Fills Identify Query Response command structure

\param[out] payload - pointer to command structure;
\param[in]  time    - identify time
******************************************************************************/
static void eclFillIdentifyQueryResponsePayload(ZCL_IdentifyQueryResponse_t *payload, uint16_t time)
{
  payload->timeout = time;
}

/**************************************************************************//**
\brief Sends Identidy Query Response command

\param[in] addressing - addressing information about sender device

\returns status of sending
******************************************************************************/
static ZCL_Status_t sendIdentifyQueryResponse(ZCL_Addressing_t *addressing)
{
  ZCL_Request_t *req;

  if (!(req = getFreeCommand()))
    return ZCL_INSUFFICIENT_SPACE_STATUS;

  fillCommandRequest(req, ZCL_IDENTIFY_CLUSTER_IDENTIFY_QUERY_RESPONSE_COMMAND_ID, sizeof(ZCL_IdentifyQueryResponse_t));
  eclFillIdentifyQueryResponsePayload((ZCL_IdentifyQueryResponse_t *)req->requestPayload, eclIdentifyClusterServerAttributes.identifyTime.value);
  fillDstAddressingViaSourceAddressing(&req->dstAddressing, addressing, ZCL_CLUSTER_SIDE_CLIENT);
  commandManagerSendCommand(req);

  return ZCL_SUCCESS_STATUS;
}

/**************************************************************************//**
\brief Makes device to start identify itself

\param[in] time - identifying time in seconds
******************************************************************************/
void idetifyStartIdentifyingCb(uint16_t time, void (*cb)(void))
{
  eclIdentifyClusterServerAttributes.identifyTime.value = time;
  identifycb = cb;
  identifyStart(eclIdentifyClusterServerAttributes.identifyTime.value,
                IDENTIFY_NON_COLOR_EFFECT, 0);
  
  //HAL_StopAppTimer(&identifyTimer);
  //HAL_StartAppTimer(&identifyTimer);
  (void)cb;
}

/**************************************************************************//**
\brief Adds record to a list of subscribers

\param[in] subscriber - pointer to subscriber;
******************************************************************************/
void identifySubscribe(IdentifySubscriber_t *subscriber)
{
  if (!isQueueElem(&subscribers, subscriber))
  {
    if(!putQueueElem(&subscribers, subscriber))
    {
	  /* failed to queue */
    }
  }
}

/**************************************************************************//**
\brief Sends Identify Query request

\param[in] mode - address mode;
\param[in] addr - short address of destination node;
\param[in] ep   - destination endpoint
******************************************************************************/
void identifySendIdentifyQuery(APS_AddrMode_t mode, ShortAddr_t addr, Endpoint_t ep)
{
  ZCL_Request_t *req;

  if (!(req = getFreeCommand()))
    return;

  fillCommandRequest(req, ZCL_IDENTIFY_CLUSTER_IDENTIFY_QUERY_COMMAND_ID, 0);
  fillDstAddressing(&req->dstAddressing, mode, addr, ep, IDENTIFY_CLUSTER_ID);
  commandManagerSendCommand(req);
  (void)mode, (void)addr, (void)ep;
  (void)mode;
  (void)addr;
  (void)ep;
}
#endif // APP_DEVICE_TYPE_EXTENDED_COLOR_LIGHT

// eof dlIdentifyCluster.c
